### ISSUE TITLE
Could not set metatable for object

### ISSUE THREAD

**Issue by demiurgeQuantified** [demiurgeQuantified/AccessibleFields#1]
(Reported by a Discord user)
```
ERROR: General     , 1688947470764> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: Could not set metatable for object at KahluaUtil.fail line:82.
ERROR: General     , 1688947470764> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: Could not set metatable for object
        at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
        at se.krka.kahlua.vm.KahluaThread.setmetatable(KahluaThread.java:1744)
        at se.krka.kahlua.stdlib.BaseLib.setmetatable(BaseLib.java:379)
        at se.krka.kahlua.stdlib.BaseLib.setmetatable(BaseLib.java:365)
        at se.krka.kahlua.stdlib.BaseLib.call(BaseLib.java:119)
        at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
        at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
        at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
        at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:564)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:510)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:496)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:342)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:264)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:391)
        at zombie.GameWindow.init(GameWindow.java:1206)
        at zombie.GameWindow.mainThreadInit(GameWindow.java:576)
        at zombie.GameWindow.mainThread(GameWindow.java:489)
        at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1688947470775> -----------------------------------------
STACK TRACE
-----------------------------------------
Callframe at: setmetatable
function: AccessibleFields.lua -- file: AccessibleFields.lua line # 33 | MOD: Accessible Fields
```
The ``Could not set metatable for object`` error means that the object whose metatable is being set is not a table, but is not nil. This could be being caused by another mod that replaces a class's index with a function, but that seems unlikely as it would prevent that class from being hooked.
It could be similar to the issues observed with Vector when writing the script - though it does try to be exposed, and it does *exist* in the classmetatables, Vector doesn't seem to be exposed correctly, and that caused issues when the script reached it - perhaps on certain platforms or under certain conditions other classes are also not exposed correctly.

**Comment by demiurgeQuantified** [comment]
i'm now receiving this myself, only when in debug mode, and with other mods enabled - likely a mod incompatibility

**Comment by demiurgeQuantified** [comment]
the changes in d6a2092 addressed the issue for me, but not closing until hearing back from the original reporter as they encountered it under different circumstances so it could be a separate bug to the one i experienced
